### ISSUE TITLE
Swift Sample App

### ISSUE THREAD

**Issue by karlbarek** [AzureAD/azure-activedirectory-library-for-objc#798] opened 2016-10-04 21:48 UTC
I'm getting the following error:
_ViewController.swift:38:63: Cannot convert value of type '(ADAuthenticationResult!) -> ()' to expected argument type 'ADAuthenticationCallback!'_

in the function:

```
authContext.acquireTokenWithResource("https://graph.windows.net",
                                             clientId: "b92e0ba5-f86e-4411-8e18-6b5f928d968a",
                                             redirectUri: NSURL(string: "urn:ietf:wg:oauth:2.0:oob"))
        {
            (result:ADAuthenticationResult!) in
            if (result.status != AD_SUCCEEDED)
            {
                self.updateStatusField(result.error.description)
                return;
            }

            let status = String(format: "Access token: %@\nexpiration:%@", result.accessToken, result.tokenCacheItem.expiresOn ?? "(nil)")
            self.updateStatusField(status)
        }
```

**Comment by tsteele2013** [comment] 2016-10-06 13:27
I've received the same error in my app as well. Waiting (somewhat desperately) for the team to update their documentation. If I get the time to resolve the error myself before hand, I'll be sure to post my code on here!

**Comment by brandwe** [comment] 2016-10-13 01:21
@RPangrle can you take a look? This is Swift.

**Comment by brandwe** [comment] 2016-10-13 22:48
Assigning to @jasoncoolmax to take a look.

**Comment by jasoncoolmax** [comment] 2016-10-14 06:39
@karlbarek the Swift Sample app has been updated to Swift 2.3, kindly check the dev branch. Release with such an update will be coming later.

@tsteele2013 If you project is using Swift 2.3, the above piece of code should work. 
If your project is using Swift 3.0, you can try to replace (result:ADAuthenticationResult!) with (result), although I am still not sure whether this is the optimal conversion.

**Comment by tsteele2013** [comment] 2016-10-18 19:10
@jasoncoolmax Sorry, didn't see that you'd responded. Thanks for getting back with a resolution so quickly... The error went away, So after I'm able to build my project, I'll let you know if your fix was successful. Thanks!

**Comment by RPangrle** [comment] 2016-11-29 23:18
This is a duplicate of #795

**Closed by RPangrle** 2016-11-29 23:18 UTC
Labels: Duplicate
