### ISSUE TITLE
iPadOS 13 ADKeychainErrorDomain -34018

### ISSUE THREAD

**Issue by jakkornat** [AzureAD/azure-activedirectory-library-for-objc#1474] opened 2019-10-02 07:42 UTC
Hi again, 

We try to support the update to iPadOS 13 but we have met that issue:

(error=Error with code: -34018 Domain: ADKeychainErrorDomain ProtocolCode:(null) Details:Failed to get items from keychain.. Inner error details: Error Domain=ADKeychainErrorDomain Code=-34018 "(null)" UserInfo={MSIDErrorDescriptionKey=Failed to get items from keychain., MSIDCorrelationIdKey=329E5CA9-8904-43A8-ADA7-2CAB9201DF17}, mrrt=NO, status=AD_FAILED, item=(null), correlationId=329E5CA9-8904-43A8-ADA7-2CAB9201DF17, authority=(null))

This is occurred in both latest 2.x and 4.x versions. 

This was not appear on previous iOS 12. 

Thanks in advance for your support.
Jakub

Edited:
Compiled with both Xcode 11 and Xcode 10.

**Comment by igoMobile** [comment] 2019-10-02 13:21
We experience the same issue since iOS 13

**Comment by jakkornat** [comment] 2019-10-02 14:00
@igoMobile  If you need the "quick win" workaround, then let's try to add Keychain Sharing access group in the target capabilities. It seems that the bug is probably connected with sharing keychain access between app (or modules) so that I've added two ids to keychain access group: 

<img width="851" alt="Screenshot 2019-10-02 at 15 55 36" src="https://user-images.githubusercontent.com/32837423/66050347-5abaee80-e52d-11e9-8b20-871a9e8a9ca1.png">

However it was working fine even without that in iOS 12, so it's just workaround and should be fixed anyway.

**Comment by adamledwards** [comment] 2019-10-03 11:18
Hi I've also had this issue on IOS13 
I enabled the logs and found it was a keychain sharing issue and it was trying to access com.microsoft.workplacejoin

I solved this by adding both 
```
com.microsoft.workplacejoin
com.microsoft.adalcache 
```
to my keychain sharing. 

The only reference to com.microsoft.workplacejoin is in a changelog.txt 
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/0ae4f958c3722d210d08b60b22d0bed5300ba7f3/changelog.txt#L345

Using ADAL v2.7.15, Xcode 11

**Comment by igoMobile** [comment] 2019-10-04 12:43
Hey great! Thanks a lot! that fixed my issue too!

**Comment by Podiya** [comment] 2019-10-09 04:16
@adamledwards @jakkornat Thanks guys. It solved my problem also. (Y)

**Comment by charshep** [comment] 2019-10-09 22:47
We're seeing this problem in the field but we're not able to reproduce it. Can we get confirmation that this is in fact an iOS 13 issue (possibly only 13.1.2 from what we see) and that the additional keychain group is the proper fix?

**Comment by oldalton** [comment] 2019-10-11 00:14
Hi, we weren't able to reproduce the second issue locally with latest 4.x release. The first issue is expected if you don't have com.microsoft.adalcache declared in your keychain entitlements (you can also provide your own keychain group if you want to use a different one). The second issue is unexpected as com.microsoft.workplacejoin is not required. Let me try 2.7.15 to see if it's reproducible in 2.7.x.

**Comment by Podiya** [comment] 2019-10-11 04:14
In my scenario i got this error in 13.1.2. but i wanted to know this is only for 13 or not. so i checked my simulator which has 12.* something. It occurred same issue that login pop-up doesn't appear. so go through this error and found this. added those two string to keychain sharing and it was worked perfectly.

**Comment by oldalton** [comment] 2019-10-11 17:16
Ok, I'm thinking it might be a 2.7.x issue. Let me test with that version and come back. Thanks!

**Comment by oldalton** [comment] 2019-10-13 04:36
This issue will be fixed in ADAL 2.7.16: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1478.

**Comment by adamledwards** [comment] 2019-10-13 15:16
@oldalton thank you for the fix
Should we remove `com.microsoft.workplacejoin` from keychain sharing setting?
Once we have upgraded to 2.7.16

**Comment by oldalton** [comment] 2019-10-14 04:24
Wouldn't make much difference whether you keep it or remove it. To avoid confusion is probably better to remove it with 2.7.16.

**Comment by jakkornat** [comment] 2019-10-14 09:20
I've met that issue also for 4.0.3 version if not add Keychain Sharing capabilities like above.

**Comment by oldalton** [comment] 2019-10-14 17:22
@jakkornat, com.microsoft.adalcache is still required even after the fix.

**Comment by jakkornat** [comment] 2019-10-15 12:23
Ok for me.

**Comment by oldalton** [comment] 2019-10-26 00:13
Should be fixed in 2.7.16. Please reopen the issue if you're still seeing it in 2.7.16.

**Closed by oldalton** 2019-10-26 00:13 UTC

**Comment by ehynds** [comment] 2019-10-29 13:02
@oldalton Is this also fixed in 4.0.4?

**Comment by oldalton** [comment] 2019-10-29 17:46
This issue was only in 2.7.x branch, so there was no need for a fix in 4.x. 
Note that com.microsoft.adalcache is still needed in both 2.7.x and 4.x. The fix was about removing unneeded com.microsoft.workplacejoin group.
