### ISSUE TITLE
Extra whitespace before email address causes crash

### ISSUE THREAD

**Issue by joelklabo** [AzureAD/azure-activedirectory-library-for-objc#628] opened 2016-04-29 22:48 UTC
If you login with the email: "joel@somethign.com" it works. If you login with " joel@something.com" NSURL URLWithString will return nil. 

ADAuthenticationRequest+WebRequest Line 427

**Comment by jasoncoolmax** [comment] 2016-05-03 07:55
@joelklabo May I know which function did you call to log in? what are the parameters? I am trying to reproduce the issue :)

**Comment by jasoncoolmax** [comment] 2016-05-18 16:44
I cannot reproduce it. I am closing this because there is no reply from the original poster for more than 2 weeks.

**Closed by jasoncoolmax** 2016-05-18 16:44 UTC
