### ISSUE TITLE
Explicit Logout functionality

### ISSUE THREAD

**Issue by jpanchal** [AzureAD/azure-activedirectory-library-for-objc#264] opened 2015-02-17 17:05 UTC
Is there explicit logout functionality? Clear credentials method only seems to clear the cache but it is not actually logging out from the server.

**Comment by kpanwar** [comment] 2015-02-18 18:13
Logout is not currently supported in the API.

**Comment by kpanwar** [comment] 2015-02-18 18:14
Duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/77

**Closed by kpanwar** 2015-02-18 18:14 UTC

**Comment by jpanchal** [comment] 2015-02-18 19:01
Are there any plans of supporting it? Are their any alternatives to expire the token?

**Comment by kpanwar** [comment] 2015-02-18 19:04
There are no plans as of yet. You can clear your cookies from the storage. there are several code samples online to do so.

**Comment by jpanchal** [comment] 2015-02-18 19:12
I am clearing cache, which is clearing the keychain, but apparently that's not enough.

**Comment by kpanwar** [comment] 2015-02-18 19:15
Check out the sample app bundled in with ADAL SDK.
it contains the code to delete the cookies.

    NSHTTPCookieStorage* cookieStorage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
    NSArray* cookies = cookieStorage.cookies;
    if (cookies.count)
    {
        for(NSHTTPCookie* cookie in cookies)
        {
            [cookieStorage deleteCookie:cookie];
        }
        status = [status stringByAppendingString:@" Cookies cleared."];
    }

**Comment by jpanchal** [comment] 2015-02-18 19:22
Thanks. I wonder if clearing all the cookies is a good idea.

**Comment by kpanwar** [comment] 2015-02-18 19:27
Cookies are cleared for the webview in the your app. You should be okay unless you also use webview for other tasks.

**Comment by kpanwar** [comment] 2015-02-19 06:44
What is your end goal though? Make a user prompt for credentials? If so, then you can pass promptbehavior as always to the API. It will guarantee that the user is prompted for password

**Comment by jpanchal** [comment] 2015-02-19 17:02
We want to make sure when user is logged out, they are completely denied for any further access. We have some background task, polling for data. Prompting for credentials is not actually logging out. For now, I have cleared the cookies.
