### ISSUE TITLE
Couldnt able to get Policy list using accesstoken Generated from MSAL library

### ISSUE THREAD

**Issue by sw-tt-rumitkkhakhi** [AzureAD/azure-activedirectory-library-for-objc#1567] opened 2021-01-29 12:49 UTC
Hello All,

I am using MSAL library to authenticate the user and also we are using C++ library to get the Policylist. We are passing accesstoken in C++ library which is generated from MSAL. But i can not get the policy list. I am getting below error from C++ SDK,

ERROR - Unexpected exception: 'The service didn't accept the auth token. Challenge:['']'
Program ended with exit code: 255

Also I have passed below scope when authentiate the user.

let kScopes: [String] = ["https://graph.microsoft.com/.default"]

Please let me know what i have to do to resolve it.

Note: Also if we are parsing accesstoken generated from ADAL library to C++ SDK, it's works. We also noticed that length  of accesstoken generated from MSAL and ADAL are different.

Thanks,
Rumit

**Comment by antrix1989** [comment] 2021-01-29 23:14
Hi @sw-tt-rumitkkhakhi , which C++ library do you use?

**Comment by sw-tt-rumitkkhakhi** [comment] 2021-02-01 09:16
Hello Sergery,

We are creating MacOS app and we have downloaded “mip_sdk_macos_1.7.145.tar.gz” and using it for our development.

There are 3 parts of “mip_sdk_macos_1.7.145.tar.gz” when we unzipped it.

1) file
2) protection
3) upe

So we have created a MacOS sample where we have integrated 3rd option “upe” classes to get policy list initially.

We have integrated MSAL framework in our MacOS app to authenticate the user and if user is authenticated successfully then we are using access-token (Generated using MSAL token) to get PolicyList using above sample code. We are passing token to above code instead of using username and password. I have added below scope with authentication in MSAL code.

 let kScopes: [String] = ["https://graph.microsoft.com/.default”]

but we can’t get policy-list from above sample code link as it is throwing error like

ERROR - Unexpected exception: 'The service didn't accept the auth token. Challenge:['']'

So, Why we can not use MSAL access-token in MIP SDK ?


Using ADAL framework

Also we noticed that if we authenticate using ADAL framework and if we use access-token generated using ADAL and pass to above sample code (upe) we are successfully getting the policyList.

Also another thing we noticed that if we use use ADAL framework to authenticate the user and getting policy list successfully if we use same ADAL access token to protect the file, we can’t. Please suggest as we are stuck on every part in development using this C++ SDK.


We are looking for your reply.


Thanks,
Rumit

**Comment by sw-tt-rumitkkhakhi** [comment] 2021-02-02 13:06
Hello

Any update on it ? I want to move forward with this sdk.

**Comment by sw-tt-rumitkkhakhi** [comment] 2021-02-09 07:18
I am waiting for your reply. Can you please give us any suggestion on this ? We are still facing this issue.

**Comment by antrix1989** [comment] 2021-02-11 02:10
Hi @sw-tt-rumitkkhakhi, so you are using [Microsoft Information Protection SDK](https://docs.microsoft.com/en-us/information-protection/develop/). Please change your `kScopes` constant. It should be: 
`<your resource>/.default`

See the example [here](https://docs.microsoft.com/en-us/information-protection/develop/concept-auth-scenario-csharp).

**Comment by ameyapat** [comment] 2021-02-16 23:55
@sw-tt-rumitkkhakhi Closing issue for now. Please reopen if the issue is still there.

**Closed by ameyapat** 2021-02-16 23:55 UTC
Labels: Question
