### ISSUE TITLE
KeychainTokenCacheStore doesn't work by default sharedGroup is explicitly set to nil

### ISSUE THREAD

**Issue by samirahmed** [AzureAD/azure-activedirectory-library-for-objc#274] opened 2015-03-04 19:04 UTC
I have found an issue (after 2 days of debugging ... :sob: ) which results in the `ADKeychainTokenCacheStore` failing silently and triggering `AD_ERROR_USER_INPUT_NEEDED`

In the latest version ... `1.2.1` the `ADKeychainTokenCacheStore` is initialized by default with a shared group [in this commit](https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/d107bb55d8e7ba54d84038e1d50e79de293f4cc7#diff-5ca732cc8853566388d1cef0aacad952R53)

Unfortunately that change combined with this [change to set the accessToken](https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/d107bb55d8e7ba54d84038e1d50e79de293f4cc7#diff-e0907fea53b08f53ca383d4e86fd0040R52) means that a shared access group is always set. 

I don't know if this is intentional or not but I do know that in the previous version since `sharedGroup` would default to `nil` it would work and by updating to `1.2.1` it has broken my app.

Whats worse is that since there is a macro that [skips the sharedGroup check in the simulator](https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/d107bb55d8e7ba54d84038e1d50e79de293f4cc7#diff-e0907fea53b08f53ca383d4e86fd0040R73) ... this problem only reproduces on the device and not the simulator making it very tricky to actually find.

The symptoms of this issue are that an explicit user prompted auth succeeds... but then all silent calls fail since the TokenCache has zero tokens in it (not sure where/why the exact failure comes from)

To ensure that this was a problem with the `ADKeychainTokenCacheStore` I created an in memory token Cache store myself ... and verified that this was indeed the problem

**Comment by kpanwar** [comment] 2015-03-04 19:06
What version were you using before?

**Comment by samirahmed** [comment] 2015-03-04 19:10
I was using `1.0.2` in my previous app.  

Created a new app with same version ... and hit the issue about not being able to set the parentViewController (now fixed) so I moved to the `1.2.1` and was baffled by this issue

**Comment by kpanwar** [comment] 2015-03-04 19:13
please check out the change logs for all the updates and fixes. I am closing this issue because it is by design. Having a default value sets a clear story for sharing cache across multiple apps from the same publisher. Imagine all the MS products using a different cache name and not being able to share tokens.

**Closed by kpanwar** 2015-03-04 19:13 UTC
