### ISSUE TITLE
My App crashing  at login (Access your originization data webpage)after updating  to ADAL ios 4.0.0 version. 

### ISSUE THREAD

**Issue by kiara544** [AzureAD/azure-activedirectory-library-for-objc#1385] opened 2019-02-26 17:53 UTC
I also added exception break points and i see crash is happening in MSIDOAuth2EmbeddedWebviewController.m class in the ADAL SDK

<img width="2047" alt="adal-crash" src="https://user-images.githubusercontent.com/44411947/53434816-03640700-39bd-11e9-86d2-2ac99ec19038.png">

**Comment by oldalton** [comment] 2019-02-27 19:13
Thanks, we're looking into it if it's an incompatibility between MAM SDK and ADAL 4.0.0. In the meantime, please use ADAL 2.7.x as a workaround.

**Comment by oldalton** [comment] 2019-02-27 19:14
@rohitnarula7176, assigning you to this one.

**Comment by kiara544** [comment] 2019-03-13 14:38
Any updates on this issue ?

**Comment by antrix1989** [comment] 2019-03-14 00:57
Please check `webView` property of `ADAuthenticationContext` and make sure you are passing an instance of `WKWebView`, **not** `UIWebView`. As Olga mentioned above, we moved away from UIWebView in ADAL 4.0.0.

**Comment by kiara544** [comment] 2019-03-15 15:08
I double checked and made sure my app is not pass any webview instance. During debug i found that webview defined as WKWebview  in MSIDOAuth2EmbeddedWebviewController.m is still returns UIWebview instance when value is printed. Please see attached screenshot
![Screenshot](https://user-images.githubusercontent.com/44411947/54441208-42f35880-470a-11e9-80fe-09e38ae99f61.jpg)

**Comment by antrix1989** [comment] 2019-03-15 16:41
`UIWebview` is definitely coming outside of ADAL. Please catch a breakpoint in `ADAuthenticationContext acquireTokenWithResource:...` (line 14 in your stack trace) and print `webView` property:
`po self.webView`

If it is not nil, then you are passing it to ADAL.

**Comment by kiara544** [comment] 2019-03-15 19:16
I am getting nil when i print webview property
![Screen Shot 2019-03-15 at 1 31 04 PM](https://user-images.githubusercontent.com/44411947/54456601-f705db00-472c-11e9-9db1-1759dc613789.jpg)

**Comment by antrix1989** [comment] 2019-03-15 19:59
This happens because MAM SDK doesn't support ADAL 4.0.0. Please downgrade ADAL to 2.7.x until we add WKWebView support into MAM SDK.

**Comment by kiara544** [comment] 2019-08-03 14:44
Hello, I am seeing the same crash again after updating Intune (11.0.8) and Adal (4.0.1) but this time 
webView property: is not coming back as Nil i am getting UIWebview and i also made sure that i am not passing an instance of UIWebView.

**Comment by kiara544** [comment] 2019-08-05 14:45
This issue doesn't happen after updating Intune (11.0.8) with ADAL (2.7.13) webView property is coming back as Nil.

**Comment by kiara544** [comment] 2019-08-08 21:49
Any update on this issue?

**Comment by oldalton** [comment] 2019-08-08 21:55
@kiara544, please use latest Intune SDK (11.0.13): https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/11.0.13

**Comment by kiara544** [comment] 2019-08-08 22:24
Does new version of Intune SDK(11.0.13) also support ADAL 4.0.1 ? I am still seeing a crash at login after updating Intune SDK

**Comment by oldalton** [comment] 2019-08-08 22:26
There haven't been any changes related to web views between 4.0.0 and 4.0.1, so I don't think there should be any differences. Is it the same crash? Are you seeing the same with 11.0.13 and 4.0.0?

**Comment by kiara544** [comment] 2019-08-09 04:26
Yes the same place. Please see the attached screenshot.

**Comment by oldalton** [comment] 2019-08-11 05:17
@kiara544, thanks for reporting this. I've confirmed with latest MAM SDK that the issue indeed hasn't been resolved. Looking at the symbols of Intune MAM SDK release, looks like ADAL 4.x support is not included. I've followed up with Intune MAM SDK team to see if there was a mistake, and will update you once I hear from them. Thanks and sorry for the trouble!

**Comment by oldalton** [comment] 2019-11-13 19:34
This should be fixed now. Please retry with the latest MAM SDK.

**Closed by oldalton** 2019-11-13 19:34 UTC
Labels: Question

**Comment by pgawlowski** [comment] 2019-12-19 11:14
Still same problem
