### ISSUE TITLE
ADAL does not return error when user hits 'cancel' on the app switch permission dialog

### ISSUE THREAD

**Issue by dimabs** [AzureAD/azure-activedirectory-library-for-objc#656] opened 2016-06-01 16:41 UTC
When invoking broker, user is asked for permissions to open Azure Authenticator. If user clicks 'Cancel', ADAL is not raising error, and obviously not returning success, which is expected. We should get back error indicating that user canceled operation

**Comment by RPangrle** [comment] 2016-08-09 19:21
This specific case is difficult because the OS does not let us know that the user chose not to allow the app to switch. The best we'll be able to do is use a timeout, but we're undecided on that.

**Comment by RPangrle** [comment] 2016-12-12 22:04
There's no way we can accurately give an error because the OS doesn't let us know. Closing as By Design/Apple

**Closed by RPangrle** 2016-12-12 22:04 UTC
Labels: Apple, By Design
