### ISSUE TITLE
User not decoded on WebView

### ISSUE THREAD

**Issue by SagarPrajapati98** [AzureAD/azure-activedirectory-library-for-objc#1508] opened 2020-01-20 12:35 UTC
When passing loginhint the actual value is different on the username textbox i think it's not decoded before displaying 

i am passing the loginhint by encoding by URLEncode but it's not decoded in webview it shows % and kind of value

**Comment by oldalton** [comment] 2020-01-24 16:48
Looks like a duplicate of this one: https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1509

Can you please take a look at the resolution of that one and let me know if it resolves your issue as well.

**Comment by oldalton** [comment] 2020-01-28 22:41
Closing this issue as it should be resolved in the latest ADAL version. Please reopen if you're still experiencing the issue. Thanks!

**Closed by oldalton** 2020-01-28 22:41 UTC
Labels: Question
