### ISSUE TITLE
Update whitelist of known authorities

### ISSUE THREAD

**Issue by RandalliLama** [AzureAD/azure-activedirectory-library-for-objc#263] opened 2015-02-16 20:19 UTC
login.microsoftonline.com needs to be added to the whitelist of common authorities.

**Comment by kpanwar** [comment] 2015-02-16 20:26
Duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/246 and it has already been fixed

**Closed by kpanwar** 2015-02-16 20:26 UTC
Labels: P0
