### ISSUE TITLE
Cancel OpenURL permission alert in iOS is not handled. Need to handle completion of OpenURL.

### ISSUE THREAD

**Issue by imvjhere** [AzureAD/azure-activedirectory-library-for-objc#880] opened 2017-01-25 13:52 UTC
1. When App is installed for the 1st time, during authentication, alert appears to allow open -authenticator. 
2. If user select 'cancel' - It wouldn't be handled.

There needs to be some provision in (void)sharedApplicationOpenURL:(NSURL*)url in ADAppExtensionUtil to deal with this scenario.

**Comment by RPangrle** [comment] 2017-02-11 02:34
Duplicate of #656

Apple does not provide a way for the developer to know that the user hit cancel, openURL still returns true in that case.

**Closed by RPangrle** 2017-02-11 02:34 UTC
Labels: Duplicate, External
