### ISSUE TITLE
Crash in promptBrokerInstall

### ISSUE THREAD

**Issue by kristoferreierson** [AzureAD/azure-activedirectory-library-for-objc#846] opened 2016-11-30 16:20 UTC
While doing testing on a ctip account, I found that + (void)promptBrokerInstall:(NSDictionary *)brokerParams
          completionHandler:(ADAuthenticationCallback)completion

will cause the app to crash.

The code: 
    NSString* url = [qpDict valueForKey:@"app_link"];

Assumes that url will never be null and calls:
         [ADAppExtensionUtil sharedApplicationOpenURL:[[NSURL alloc] initWithString:url]];

However, if url is nil, (and I have a user with a repro if you need it) then you receive this call stack:

Error]:Caught unhandled exception name=NSInvalidArgumentException, reason=*** -[NSURL initWithString:relativeToURL:]: nil string parameter, stackTrace=(
	0   CoreFoundation                      0x0000000182d4edc8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001823b3f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182d4ecf8 <redacted> + 0
	3   Foundation                          0x000000018365568c <redacted> + 108
	4   ADAL                                0x00000001033ad5d8 __56+[ADBrokerHelper promptBrokerInstall:completionHandler:]_block_invoke + 60
	5   libdispatch.dylib                   0x00000001057d5a7c _dispatch_call_block_and_release + 24
	6   libdispatch.dylib                   0x00000001057d5a3c _dispatch_client_callout + 16
	7   libdispatch.dylib                   0x00000001057db4e4 _dispatch_main_queue_callback_4CF + 2096
	8   CoreFoundation                      0x0000000182d04d50 <redacted> + 12
	9   CoreFoundation                      0x0000000182d02bb8 <redacted> + 1628
	10  CoreFoundation                      0x0000000182c2cc50 CFRunLoopRunSpecific + 384
	11  GraphicsServices                    0x0000000184514088 GSEventRunModal + 180
	12  UIKit                               0x0000000187f12088 UIApplicationMain + 204
	13  app-ios                             0x0000000100104320 UIApplicationMain + 264
	14  app-ios                             0x00000001001b26c4 main + 204
	15  libdyld.dylib                       0x00000001827ca8b8 <redacted> + 4

**Comment by RPangrle** [comment] 2016-11-30 19:37
Duplicate of #818

**Closed by RPangrle** 2016-11-30 19:37 UTC
Labels: Duplicate
